[server]
headless = true
port = 8510
runOnSave = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#1700F3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F3F3"
textColor = "#00095B"
