[server]
headless = true
port = 8510
runOnSave = false
maxUploadSize = 1024

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
primaryColor = "#1700F3"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#00095B"
font = "sans serif"
